// eventData.js
export const eventData = {
    'cyberquest': {
        img: 'card_abstract',
        title: 'CyberQuest',
        tagline: "Race Against Time, Conquer the Treasure!",
        team_size: 3,
        description: 'In this exciting treasure hunt, 30 teams race to solve clues, follow hidden paths, and find the final treasure. Teams log into a website, enter clues, and move to the next step. With only a few hints available, quick thinking and smart choices are important. The team that solves the most clues with the fewest hints wins. Get ready for a fun and challenging adventure!',
        rules: [
            'Team Formation: 30 teams, with 3 members in each team (total of 90 participants).',
            'Clue Solving: Each team must log in to the treasure hunt website using their team name and login.',
            'Following Clues: Teams will enter a clue, move to the next location, and continue solving until they reach the final treasure.',
            'Hints: Teams are given 3 hints to use if they cannot solve a clue.',
            'Time Limit: Teams must complete the treasure hunt in the given time.',
            'Winner: The team that solves the most clues with the fewest hints wins.',
            'Evaluation: Teams will be judged based on how many clues they solve and the number of hints used.',
        ],
    },
    'aadukalam': {
        img: 'card_abstract_two',
        title: 'Aadukalam',
        tagline: "DSA Battlefield",
        team_size: '2 - 3',
        description: 'the short description is long enough ig',
        rules: [
            'Eligibility: Open to all year students from all departments of the college. Registration is mandatory for participation.',
            'Contest Format:',
            '  Round 1 (Online):',
            '    Free entry.',
            '    5 questions, 2 hours.',
            '    Platform: HackerRank.',
            '    Top 50 from Round 1 qualify for Round 2.',
            '  Round 2 (Offline):',
            '    100 INR entry fee.',
        ],
    },
    'database-duel-design': {
        img: 'card_abstract',
        title: 'Database Design Duel',
        tagline: "Two Minds, One Database - Will Yours Lead the Way?",
        team_size: 2,
        description: 'Join the ultimate 2-hour challenge where teams race against the clock to design the most efficient, scalable, and innovative database schema. With a real-world problem to solve, this event tests your creativity, technical skills, and ability to think on your feet. Collaborate, compete, and see who will be crowned the ultimate DB architect!',
        rules: [
            'Teams of two participants.',
            'MCQ quiz at the beginning to refresh database concepts.',
            'Problem statement assigned via coin toss (2 options).',
            '2-hour time limit to design the database schema.',
            'Laptop is required for the event. Draw.io (online tool) will be used.',
            'Evaluation based on efficiency, scalability, and creativity.',
        ],
    },
    'flutter-frenzy': {
        img: 'card_abstract_two',
        title: 'Flutter Frenzy',
        tagline: "Flutter Your Way to Innovation",
        team_size: 1,
        description: 'A workshop covering Flutter fundamentals and building basic apps.',
        rules: [
            'Participants must bring their own laptop.',
            'Participants must complete installation prior to the event.',
        ],
    },
    'web-wizard-relay': {
        img: 'card_abstract_two',
        title: 'Web Wizard Relay',
        tagline: "Code. Collaborate. Create.",
        team_size: 1,
        description: 'The web relay is a dynamic 3-hour coding event where teams of two collaboratively build a website based on a given theme. Each team member alternates coding every 30 minutes, with only 10 minutes allowed for initial discussion. Communication during the competition is strictly through code comments',
        rules: [
            'Teams of 2 members.',
            '1.5-hour event with 10 minutes for discussion.',
            'Swap coding every 30 minutes.',
            'Only code comments allowed for communication.',
            'Theme will be provided on the event day.',
            'AI tools like ChatGPT can be used.',
            'Onus quiz to boost final scores.',
            'Judged on creativity, functionality, and theme adherence.',
        ],
    },
    'pixel-verse': {
        img: 'card_abstract_two',
        title: 'Pixel Verse',
        tagline: 'Please provide tagline',
        team_size: 1,
        description: `This workshop covers essential techniques, from mastering ISO, aperture, and shutter speed to capturing perfect candid and posed shots. Participants will engage in live practice sessions, interactive quizzes, and receive real-time feedback. Whether you’re a beginner or an enthusiast, this event offers expert insights, practical learning, and networking opportunities. Plus, stand a chance to win exciting prizes and get a participation certificate!`,
        rules: [
            'Participants must bring their own cameras or smartphones for hands-on practice.',
            'Respect the time limits for each activity to ensure smooth session flow.',
            'Engage actively in discussions, Q&A, and practical tasks.',
            'Follow workshop guidelines and respect fellow participants and mentors.',
        ],
    },
    'chamber-of-secrets': {
        img: 'card_abstract_two',
        title: 'Chamber of Secrets',
        tagline: "Time's Not Your Friend—But Your Mind Might Be!",
        team_size: 2,
        description: 'Participants will navigate a series of puzzles and challenges to "escape" from a simulated scenario. Each stage will test their reading, writing, listening, and speaking, immersing them in a thrilling race against time.',
        rules: [
            'Teams must consist of 2 participants.',
            'The event is time-bound: 90 minutes to complete all challenges.',
            'Teams must solve challenges in sequence; skipping a stage is not allowed.',
            'Only one clue can be requested per team, with a time penalty of 5 minutes.',
        ],
    },
    'pitch-perfect': {
        img: 'card_abstract_two',
        title: 'Pitch perfect',
        tagline: "Express Ideas, Inspire Minds",
        team_size: '3 - 5',
        description: 'Teams of 3 to 5 members will present their research or ideas using a PPT presentation,The event focuses on innovation, presentation skills, and teamwork, with judges evaluating content clarity and impact.',
        rules: [
            'Each team must have 3 to 5 members.',
            'Each team will have a maximum of 10 minutes for the presentation.',
            'An alarm will be given at 8 minutes as a reminder.',
            'Presentations must be in PPT format and must be original.',
            'All team members must participate in the presentation.',
            'The content must be original and plagiarism-free.',
            'Use of offensive or inappropriate content is strictly prohibited.',
            `Judges' decisions will be final and binding.`,
        ],
    },
    'beyond-the-screen': {
        img: 'card_abstract_two',
        title: 'Beyond the Screen: 3D Web Design Mastery',
        tagline: "From Concept to Creation: Shaping Brands of Tomorrow.",
        team_size: 1,
        description: 'Pathway to ideate the marketing path for a product and brand marketing stratergies along with entrepreneurship tips and Having an activity which will give the students the creative freedom to create their own logo for the brand or product they are given',
        rules: []
    },
};
